# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [6]:
import torch

Construct a 5x3 matrix, uninitialized

In [7]:
x = torch.Tensor(5, 3)
print(x)

tensor([[ 4.8286e-38,  4.2326e+21,  1.0745e-38],
        [-1.1984e+30,  1.1353e+30,  2.3069e-37],
        [ 7.4161e+31,  2.1160e-37,  4.5545e+30],
        [ 7.0065e-45,  1.1353e+30,  2.3069e-37],
        [ 2.1159e-37,  9.1526e+02,  1.2147e-38]])


Construct a randomly initialized matrix

In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3335, 0.6085, 0.9518],
        [0.3785, 0.9986, 0.3209],
        [0.3263, 0.2530, 0.9827],
        [0.8311, 0.1155, 0.2374],
        [0.1192, 0.7807, 0.4735]])


Get its size

In [9]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [10]:
x[1:3] = 2
print(x)

tensor([[0.3335, 0.6085, 0.9518],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.8311, 0.1155, 0.2374],
        [0.1192, 0.7807, 0.4735]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.1785, 0.8547, 1.2741],
        [2.5824, 2.1200, 2.7555],
        [2.4957, 2.5522, 2.3669],
        [1.2422, 0.6441, 0.3528],
        [0.5050, 1.6236, 1.3184]])


### 2.2 Addition: syntax 2

In [12]:
print(torch.add(x, y))

tensor([[1.1785, 0.8547, 1.2741],
        [2.5824, 2.1200, 2.7555],
        [2.4957, 2.5522, 2.3669],
        [1.2422, 0.6441, 0.3528],
        [0.5050, 1.6236, 1.3184]])


### 2.3 Addition: giving an output tensor

In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.1785, 0.8547, 1.2741],
        [2.5824, 2.1200, 2.7555],
        [2.4957, 2.5522, 2.3669],
        [1.2422, 0.6441, 0.3528],
        [0.5050, 1.6236, 1.3184]])


### 2.4 Addition: in-place

adds `x`to `y`

In [14]:
y.add_(x)
print(y)

tensor([[1.1785, 0.8547, 1.2741],
        [2.5824, 2.1200, 2.7555],
        [2.4957, 2.5522, 2.3669],
        [1.2422, 0.6441, 0.3528],
        [0.5050, 1.6236, 1.3184]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [15]:
print(x[:, 1])

tensor([0.6085, 2.0000, 2.0000, 0.1155, 0.7807])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [20]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[0.3335, 0.6085, 0.9518],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.8311, 0.1155, 0.2374],
        [0.1192, 0.7807, 0.4735]], device='cuda:0')
tensor([[1.1785, 0.8547, 1.2741],
        [2.5824, 2.1200, 2.7555],
        [2.4957, 2.5522, 2.3669],
        [1.2422, 0.6441, 0.3528],
        [0.5050, 1.6236, 1.3184]], device='cuda:0')
tensor([[1.5120, 1.4631, 2.2258],
        [4.5824, 4.1200, 4.7555],
        [4.4957, 4.5522, 4.3669],
        [2.0733, 0.7596, 0.5902],
        [0.6243, 2.4043, 1.7918]], device='cuda:0')
